# https://taskfile.dev

version: '3'

tasks:
  dev-zip:
    desc: "Creates a notebook zip file"
    run: when_changed
    sources:
      - tutorials/notebooks/**/*
    cmds:
      - git clean -fdx tutorials/notebooks
      - cd tutorials/ && zip -9 -r notebooks.zip ./notebooks
